name:                partest
version:             0.1.0.0
github:              "HEIGE-PCloud/partest"
license:             GPL-2
author:              "PCloud"
maintainer:          "heige.pcloud@outlook.com"
copyright:           "(c) 2024 PCloud"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Property based testing for context free grammar parsers
category:            Testing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HEIGE-PCloud/partest#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- containers
- gigaparsec >= 0.2 && < 0.3
- mtl
- extra

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  partest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - partest

tests:
  partest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - partest
